### ISSUE TITLE
dbName ="lireddit" Invalid shorthand property intliazer

### ISSUE THREAD

**Issue by kashif612** [benawad/lireddit#43]
C:\Users\dell\Desktop\project\dist\mikro-orm.config.js:11
    dbName = 'lireddit',
    ^^^^^^^^^^^^^^^^^^^

SyntaxError: Invalid shorthand property initializer    at wrapSafe (internal/modules/cjs/loader.js:992:16)
    at Module._compile (internal/modules/cjs/loader.js:1040:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:941:32)
    at Function.Module._load (internal/modules/cjs/loader.js:782:14)
    at Module.require (internal/modules/cjs/loader.js:965:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (C:\Users\dell\Desktop\project\dist\index.js:8:44)
    at Module._compile (internal/modules/cjs/loader.js:1076:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
[nodemon] app crashed - waiting for file changes before starting...

**Comment by kashif612** [comment]
sorry my mistake i have dbName = "" but the calling an object done by dbName : " "

**Comment by aseerkt** [comment]
@kashif612 close the issue

**Comment by kashif612** [comment]
Hi,

Sorry for the late reply the mistake done by me not ben i will do that and
now i am enjoying the tutorial and try to end up by tomorrow
Thanks&Regards

kashif
